# previewsEnabled: true
# previewsExpireAfterDays: 7 # automatically delete the environment after the specified number of days of inactivity
services:
  - type: web
    name: trpc-websockets
    env: node
    plan: free
    # NODE_ENV is development here in order for pnpm to install dev deps
    buildCommand: NODE_ENV=development pnpm install && pnpm build
    startCommand: pnpm start
    healthCheckPath: /api/trpc/healthcheck
    # Preview Environment Initialization
    # initialDeployHook: |
    #   pnpm run db-seed
    envVars:
      - key: NODE_ENV
        value: production

      - key: DATABASE_URL
        value: postgresql://postgres:b53NY5tGZz70nd2jbPPs@containers-us-west-109.railway.app:5896/railway
